#!/bin/bash -e
#
# Check whether code linting passes.

APP='pybuoy'

if [ -d '.venv' ] ; then
    PREFIX='.venv/bin/'
else
    PREFIX=''
fi

CURRENT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
BASE_DIR="$(dirname "$CURRENT_DIR")"

${PREFIX}ruff check
${PREFIX}mypy --config-file "${BASE_DIR}/pyproject.toml" -p "${APP}"
