#!/bin/bash -e
#
# Run code linting.

APP='pybuoy'

CURRENT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
BASE_DIR="$(dirname "$CURRENT_DIR")"

if [ -d '.venv' ] ; then
    PREFIX='.venv/bin/'
else
    PREFIX=''
fi

${PREFIX}black --config "${BASE_DIR}/pyproject.toml" "${BASE_DIR}"
${PREFIX}isort --settings-path "${BASE_DIR}/pyproject.toml" "${BASE_DIR}"
${PREFIX}flake8 --config="${BASE_DIR}/.flake8" "${BASE_DIR}/${APP}"
