#!/bin/bash -e
#
# Run code linting.

if [ -d '.venv' ] ; then
    PREFIX='.venv/bin/'
else
    PREFIX=''
fi

${PREFIX}ruff check --select I --fix # until unified command is added to format and sort imports
${PREFIX}ruff format
